### PR TITLE
Removes the manual build task step

### PR DESCRIPTION
**Pull request by abea**

### CODE REVIEW

**Comment by abea** [comment]
Should this point to beta instead? We could hold off merging until beta release.

**Review by boutell — CHANGES_REQUESTED** [review]
Yes good idea, let's hold it for the beta.

**Comment by boutell** [comment]
Who is `build` for? dev does not invoke it, so is it for deployments?

If so, it should still use the task.

**Comment by abea** [comment]
Oh, you're right. I'll revert that.

**Review by boutell — APPROVED** [review]

**Pull request merged**
